language: java
sudo: required
notifications:
  email: false
script:
- gradle test
- gradle build
before_install:
- openssl aes-256-cbc -K $encrypted_9d8ead8261df_key -iv $encrypted_9d8ead8261df_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
